#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BlindsPort.Resource", IsApplication=true)]

namespace BlindsPort
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int dandelion = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int MediumTextBox = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int SmallTextBox = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int blindsContainer = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int dummybutton1 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int dummybutton2 = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int largeTextBox = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040005
			public const int app_name = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int dummy_button_one = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int dummy_button_two = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int dummy_text_large = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int dummy_text_medium = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int dummy_text_small = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
